export {
  FILE_UPLOAD,
  SUCCESS_MESSAGES,
  VALIDATION_MESSAGES as ERROR_MESSAGES,
} from '@/config';

export const ALLOWED_FILE_TYPES = FILE_UPLOAD.ALLOWED_MIME_TYPES;
export const MAX_FILE_SIZE = FILE_UPLOAD.MAX_FILE_SIZE;
export const ALLOWED_FILE_TYPES_DESCRIPTION =
  FILE_UPLOAD.ALLOWED_TYPES_DESCRIPTION;

import { FILE_UPLOAD } from '@/config';
